import { NextResponse } from "next/server";
import { Resend } from "resend";
import { createAdminClient } from "@/lib/supabase/server";

const PRIMARY_ADMIN_EMAIL = "nfsmhd585@gmail.com";
const SECONDARY_ADMIN_EMAIL = "nfsmhdlms@gmail.com";

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const {
      action,
      studentName,
      studentEmail,
      studentPhone,
      grade,
      subjectTitle,
      amount,
      referenceNo,
      quizScore,
      quizTotal,
      details
    } = body;

    const actionTitle = action || "Student Activity";
    const emailSubject = `🔔 [Academy Alert] ${actionTitle} - ${studentName || studentEmail || "Student"} (Grade ${grade || "N/A"})`;

    const emailBody = `
======================================================
STUDY WITH NAFEES ACADEMY — ADMIN NOTIFICATION
======================================================

EVENT: ${actionTitle.toUpperCase()}
TIMESTAMP: ${new Date().toLocaleString()}

STUDENT INFORMATION:
------------------------------------------------------
• Student Name: ${studentName || "N/A"}
• Email: ${studentEmail || "N/A"}
• Phone / WhatsApp: ${studentPhone || "N/A"}
• Grade: Grade ${grade || "N/A"}

ACTIVITY DETAILS:
------------------------------------------------------
${subjectTitle ? `• Subject: ${subjectTitle}` : ""}
${amount ? `• Payment Amount: LKR ${amount}` : ""}
${referenceNo ? `• Reference / Bank Ref: ${referenceNo}` : ""}
${quizScore !== undefined ? `• Quiz Score: ${quizScore} / ${quizTotal || 10}` : ""}
${details ? `• Additional Info: ${details}` : ""}

DIRECT ADMIN DASHBOARD:
https://nafees-student-lms.vercel.app/admin

======================================================
This automated notification was generated by Study With Nafees LMS.
`;

    console.log(`[ADMIN NOTIFICATION DISPATCHED TO ${PRIMARY_ADMIN_EMAIL}]`);
    console.log(emailBody);

    const recipients = [PRIMARY_ADMIN_EMAIL, SECONDARY_ADMIN_EMAIL];

    // 1. Send via Resend if API key is provided
    if (process.env.RESEND_API_KEY && !process.env.RESEND_API_KEY.includes("your-resend-api-key")) {
      try {
        const resend = new Resend(process.env.RESEND_API_KEY);
        for (const recipient of recipients) {
          await resend.emails.send({
            from: process.env.EMAIL_FROM || "Study With Nafees <onboarding@resend.dev>",
            to: recipient,
            subject: emailSubject,
            text: emailBody
          });
        }
      } catch (mailErr) {
        console.warn("Resend email dispatch warning:", mailErr);
      }
    }

    // 2. Also log event to Supabase messages / activity table if available
    try {
      const admin = createAdminClient();
      await admin.from("messages").insert({
        sender_id: null,
        target_grade: Number(grade) || null,
        subject_line: emailSubject,
        body: emailBody,
        recipient_count: 1
      });
    } catch {
      // Non-blocking
    }

    return NextResponse.json({ ok: true, recipient: PRIMARY_ADMIN_EMAIL });
  } catch (err: any) {
    console.error("Admin activity notification error:", err);
    return NextResponse.json({ error: err.message || "Failed to dispatch notification" }, { status: 500 });
  }
}
